version: '3.8'
services:

    # PHP
    app:
        build:
            context: ./docker
        container_name: app
        restart: always
        working_dir: /var/www/
        volumes:
            - ./:/var/www
        networks:
            - app_network

# Docker network
networks:
    app_network:
        driver: bridge
